server:
  port: 8081

spring:
  redis:
    cluster: # 各 Redis 节点信息
      nodes: 192.168.31.226:7001,192.168.31.226:7002,192.168.31.225:7003,192.168.31.225:7004,192.168.31.224:7005,192.168.31.224:7006
      # 执行命令超时时间
      command-timeout: 15000
      # 重试次数
      max-attempts: 5
      # 跨集群执行命令时要遵循的最大重定向数量
      max-redirects: 3
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 16
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1 # 连接池中的最大空闲连接
      max-idle: 8 # 连接池中的最小空闲连接
      min-idle: 0 # 是否在从池中取出连接前进行检验,如果检验失败,则从池中去除连接并尝试取出另一个
      test-on-borrow: true
  http:
    encoding:
      force: true
  application:
    name: content-shop
  main:
    allow-bean-definition-overriding: true
feign:
  hystrix:
    #开启feign的hystrix支持,默认是false
    enabled: true

#线程池配置
thread:
  corePoolSize: 20
  maxPoolSize: 400
  queueCapacity: 20

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000
        timeout:
          enabled: false

  # 打印sql
  level:
    com.eshopinventory: debug
    #自定义配置
rest:
  ReadTimeout: 35000
  ConnectTimeout: 5000