server:
  port: 10000

spring:
  application:
    name: eshop-gateway
  datasource:
    url: jdbc:mysql://192.168.31.223:3306/eshop?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: hezitao
    password: hezitao
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialSize: 5
    maxActive: 200
    minIdle: 5
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  boot:
    admin:
      client:
        url: http://127.0.0.1:9999


logging:
  config: classpath:logback.xml

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
      #是否注册到eureka
    register-with-eureka: true
    #表示eureka client间隔多久去拉取服务注册信息，默认为30秒，
    # 对于api-gateway，如果要迅速获取服务注册状态，可以缩小该值，比如5秒
    registry-fetch-interval-seconds: 3
  instance:
    # 发送心跳的间隔, 默认为30  建议为3
    lease-renewal-interval-in-seconds: 3

ribbon:
  eager-load:
    # ribbon的饥饿加载 , 默认为开启懒加载 , 所以会导致第一次请求某个微服务会出现请求超时问题
    enabled: true