spring:
  cloud:
    gateway:
      locator:
        enabled: true
      routes:
      # 用户模块
      - id: amap-inter-user
        uri: lb://amap-inter-user
        predicates:
        - Path=/user/**
        - Method=POST
        filters:
          # 解密
        - RequestDecodeGatewayFilter
          # 验签
        - RequestSignGatewayFilter
          # 签名
        - ResponseSignGatewayFilter
          # 加密
        - ResponseEncodeGatewayFilter
      # 文件服务
      - id: amap-inter-basic-file
        uri: lb://amap-inter-basic
        predicates:
        - Path=/basic/filecloud/upload
        filters:
        # 验签
        #- RequestSignGatewayFilter
        # 签名
        - ResponseSignGatewayFilter
        # 加密
        - ResponseEncodeGatewayFilter
      # 基础服务
      - id: amap-inter-basic
        uri: lb://amap-inter-basic
        predicates:
        - Path=/basic/**
        filters:
        # 验签
        - RequestSignGatewayFilter
        # 签名
        - ResponseSignGatewayFilter
      # afa适配器
      - id: amap-inter-afa
        uri: lb://amap-inter-afa
        predicates:
        - Path=/afa/**
        - Method=POST
        filters:
        # 限流配置
        #- name: RequestRateLimiter
        #  args:
        #    key-resolver: '#{@remoteAddrKeyResolver}'
        #    redis-rate-limiter.replenishRate: 50
        #    redis-rate-limiter.burstCapacity: 100
          # 降级配置
        #- name: Hystrix
        #  args:
        #    name: default
        #    fallbackUri: 'forward:/fallback'
          # 解密
        - RequestDecodeGatewayFilter
          # 验签
        - RequestSignGatewayFilter
          # 签名
        - ResponseSignGatewayFilter
          # 加密
        - ResponseEncodeGatewayFilter
    # 统计分析
      - id: amap-statistic
        uri: lb://amap-statistic
        predicates:
        - Path=/stsc/**
security:
  encode:
    # 前端密码密钥，必须16位
    key: 'amapamapamapamap'