spring:
  cloud:
    gateway:
      locator:
        enabled: true
      routes:
      # 认证中心
      - id: amap-auth
        uri: lb://amap-auth
        predicates:
        - Path=/auth/**
        filters:
          # 验证码处理
        - ImageCodeGatewayFilter
          # 前端密码解密
        - PasswordDecoderFilter
      #UPMS 模块
      - id: amap-upms
        uri: lb://amap-upms
        predicates:
        - Path=/admin/**
      # 代码生成模块
      - id: amap-codegen
        uri: lb://amap-codegen
        predicates:
        - Path=/gen/**
      # APP模块
      - id: amap-upms-manager
        uri: lb://amap-upms-manager
        predicates:
        - Path=/manager/**
      # 定时任务模块
      - id: amap-daemon
        uri: lb://amap-daemon
        predicates:
        - Path=/daemon/**
      # 分布式事务管理模块
      - id: amap-tx-manager
        uri: lb://amap-tx-manager
        predicates:
        - Path=/tx/**
     # 统计分析
      - id: amap-statistic
        uri: lb://amap-statistic
        predicates:
        - Path=/stsc/**
      - id: amap-upms-sh
        uri: lb://amap-upms-sh
        predicates:
        - Path=/sh/**

security:
  encode:
    # 前端密码密钥，必须16位
    key: 'amapamapamapamap'

# 不校验验证码终端
ignore:
  clients:
    - test
    - murge
